#!/bin/bash
# vim: set ts=4 sw=4 sts=4:

### BEGIN INIT INFO
# Provides: 		mpdhome
# Required-Start:    $local_fs $remote_fs mpd lirc
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MPD@Home project
### END INIT INFO


# MPD @ Home project

. /lib/lsb/init-functions
. /etc/mpdhome/mpdhome.conf

init_runtime() {
    # /etc/mpdhome - for configs
    # /etc/mpdhome/lirc.d - for LIRC scripts
    # /var/run/mpdhome - status of mpdhome system

    ! [ -d /etc/mpdhome ] && (mkdir /etc/mpdhome)
    ! [ -d /etc/mpdhome/lirc.d ] && (mkdir /etc/mpdhome/lirc.d)
    ! [ -d /var/run/mpdhome ] && (mkdir /var/run/mpdhome)
    ! [ -d /var/run/mpdhome/pid ] && (mkdir /var/run/mpdhome/pid)
}

start() {
    log_daemon_msg "Starting MPD@Home" "mpdhome"

    # Check for runtime directories and init them
    init_runtime

    # Run all LIRC scripts from daemon directory
    if [ -n "$MPDHOME_USE_LIRC" ]; then
        for scr in `find -L /etc/mpdhome/lirc.d -name *.lirc`; do
            fname=`echo ${scr/"/etc/mpdhome/lirc.d/"/} | tr '/' '-'`
            irexec $scr 2>/dev/null 1>/dev/null &
            echo $! > /var/run/mpdhome/pid/$fname.pid
        done
    fi
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping MPD@Home" "mpdhome"

    # Stop all running scripts
    for pid in `find /var/run/mpdhome/pid/ -name *.pid | xargs cat`; do
        kill $pid
    done

    rm -f /var/run/mpdhome/pid/*.pid

    log_end_msg $?
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 2
    ;;
esac
